### PR TITLE
Update for v2 Sentinel Upgrade

### PR DESCRIPTION
**Pull request by MathNodes**
Also, there were variables named `from` in some of the protobuf files and I had to rename them to `frm` since `from` is a python keyword. 

Please merge. ty

### CODE REVIEW

**Comment by ctrl-Felix** [comment]
Why are there two sentinel config files? Also is there a way for you to exclude the worflow tg notify please?

**Comment by MathNodes** [comment]
I just got back from vacation where there was no cell phone service, internet or TV. It was marvelous. 

Anyhow, I had two sentinel config files because one was for current and the other for the development. We are using development branch now as we prepare for the upgrade. 

I will be making a git push to update this library per your request to exclude the workflow and contain only one sentinel config file. I also noticed there was a namespace collision in v2 sentinel protobuf file that I had to fix (gogoproto)

Will push an update later this week.

**Comment by MathNodes** [comment]
Ok. I pushed it tonight. Check and verify.

**Comment by ctrl-Felix** [comment]
Can you check on the conflicts please? 
Actually, do you see them or is it only me who sees them?

**Comment by MathNodes** [comment]
All set. I removed the conflicts.

**Pull request merged**
